# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a02978f8-166b-4d7a-8052-a08b4b1ae82c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a02978f8-166b-4d7a-8052-a08b4b1ae82c".device = "/dev/disk/by-uuid/a02978f8-166b-4d7a-8052-a08b4b1ae82c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8DC4-30FC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ed6165ce-68f1-4c99-b2fd-1875a5f07219"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
